[path]
# The preparation script replaces these with absolute paths.
path_input = docs/_build/quickstart/input
path_output = docs/_build/quickstart

[input_addition]
optimal_type = 0
tectonic_stress_type = 1
tectonic_stress = [-4, 0, 0, -6, 0, -2]
mu_f = 0.4
B_pore = 0
source_inds = [1]
source_shapes = [[1, 1]]
source_ref = [0, 0]
obs_inds = [1]
obs_shapes = [[3, 1]]
obs_ref = [0, 0]
earth_model_layer_num = 24
use_spherical = False
slip_thresh = 0
cut_stf = 0
correct_zero_freq = False

[fixed_obs_depth]
fixed_obs_depth = 0
obs_lat_range = [0, 0]
obs_lon_range = [0.3, 0.8]
obs_delta_lat = 0.1
obs_delta_lon = 0.1

[grn_region]
# EDGRN needs at least two source depths.
grn_source_depth_range = [10, 11]
grn_delta_source_depth = 1
grn_obs_depth_range = [5, 5]
grn_delta_obs_depth = 1
grn_dist_unit = km
grn_dist_range = [1, 121]
grn_delta_dist = 10

[time_window]
sampling_interval_stf = 0.5
sampling_interval_cfs = 0.5
sampling_num = 256
max_frequency = 1

[parallel]
processes_num = 1
check_finished = False

[default_config]
default_config = True
